{% set name = "Represent" %}
{% set version = "1.6.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 026c0de2ee8385d1255b9c2426cd4f03fe9177ac94c09979bc601946c8493aa0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - six >=1.8.0
  run:
    - python
    - six >=1.8.0

test:
  imports:
    - represent

about:
  home: https://github.com/RazerM/represent
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Create __repr__ automatically or declaratively.'

  description: |
    Create __repr__ automatically or declaratively.
  doc_url: https://github.com/RazerM/represent
  dev_url: https://github.com/RazerM/represent

extra:
  recipe-maintainers:
    - simonvh
