travis:
  secure:
    BINSTAR_TOKEN: WU16H3gEXNbPbrnqrK6HzLlVTzs6gseOhhb9GZiwILKbA+uiP9lv9Pj/ZZ2fOy4PhXrKE8/sY/gQ3RASbvSHe42849DEzsQaUo6JSYj1yd0yhR+YmlsPtsH4YLTgY/QPwVd9UriaJGzKfr+55TfVz8Vv+UrD+HaGGYNK9/tRdeqrGrL922CHB2R3Ib1NZA1ElTaXuPc07jFPkCtwKLmNC7UrBvGUfxrAaA+f2BmEC/dK1YEpEo4LzQ4baQNbUA5+q13AGUzGZ+rphxQSyNBltvCupuSxr0JXX0FED2Iy632qMlEkauHqhkDsnnSUKi3rhjQYO3Pr3ynB0VKlQzPw4HajCO/XOQ8sbrRWJEspLEggOoANmuvvK2FSrem1PiLlnVc9NkpIluLBgKgv1/qGbopP3qK3t3xprxsP4RlIzz0+LXTWwkaCX8yPlRNv1d7byrSuzsROsAQpDaBn1nQrM7veUIV8wxS4kxyX+KBEsXdsiYwOgbfR1a8Dng55NN9xeEAx3eW8RMgfno79mE3+0SM6i70JRSbUTZ3Oj3dmINr3s0lLBdLSQeQrl6o2htfM4XboaTzeu3Ow7VZKgEXccfnVTcec1rFFZsj+q1eOBcrit9i4LXbx6Ow3V1VyQW4wj6VWW+JsuNkfcdJ7svugMdvtSP5S2w+ih/uJS2IOQvo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
